config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/page/:page" => "places#index"
  root("places#index")
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end
  resources :users, only: :show do
    get "/places/:place_page", action: :show, on: :member
    get "/comments/:comment_page", action: :show, on: :member
    get "/places/:place_page/comments/:comment_page", action: :show, on: :member
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user, inverse_of: :comments
	belongs_to :place, inverse_of: :comments

	validates :rating, presence: true

	RATING_MAP = {"Five Stars" => 5, "Four Stars" => 4, "Three Stars" => 3, "Two Stars" => 2, "One Star" => 1}
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :place, inverse_of: :photos
  mount_uploader :image, ImageUploader
  validates :image, presence: :true
  validates :caption, length: {maximum: 140}
end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :user, inverse_of: :places
	has_many :comments, inverse_of: :place, dependent: :destroy
	has_many :photos, inverse_of: :place, dependent: :destroy

	validates :name, presence: true, length: {minimum: 4}
	validates :address, presence: true
	validates :description, presence: true

	geocoded_by :address
	after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :places, inverse_of: :user, dependent: :destroy
  has_many :comments, inverse_of: :user, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :store_location

  # Store the previous URL as a user browses around and redirect to it after a sign in or sign up
  private
  def store_location
  	session[:previous_path] = request.fullpath unless request.fullpath.include?("/users") || !request.get?
	end

	def after_sign_in_path_for(resource_or_scope)
		return session[:previous_path] || root_path
	end

	def after_sign_up_path_for(resource_or_scope)
		return session[:previous_path] || root_path
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		comment = Comment.create comment_params.merge({user_id: current_user.id, place_id: params[:place_id]})
    NotificationMailer.comment_added(comment).deliver_later
		redirect_to place_path(params[:place_id])
	end

	private
	def comment_params
		return params.require(:comment).permit(:message, :rating)
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :authenticate_user!

	def create
    @comment = Comment.new # Allows for full functionality if the render below happens
		place_id = params[:place_id]
		@place = Place.find(place_id)
		return render text: "This action is not allowed", status: :forbidden if current_user.id != @place.user_id
		@photo = Photo.new photo_params.merge(place_id: place_id)
    if @photo.save
      redirect_to place_path(place_id)
    else
      render "places/show"
    end
	end

  # Takes care of an otherwise invalid route exposed by the render above
  def index
    return redirect_to place_path(params[:place_id])
  end

	private
	def photo_params
		return params.require(:photo).permit(:image, :caption)
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.page(params[:page]).per(3)
  end

  def new
  	@place = Place.new
  end

  def create
  	@place = Place.new(place_params.merge(user_id: current_user.id))
  	if @place.save
      redirect_to place_path(@place)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])
    render text: "You are not allowed to access this page", status: :forbidden if current_user.id != @place.user_id
  end

  def update
    @place = Place.find(params[:id])
    return render text: "This action is not allowed", status: :forbidden if current_user.id != @place.user_id
    if @place.update_attributes(place_params.merge(user_id: current_user.id))
      redirect_to place_path(@place)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    return render text: "This action is not allowed", status: :forbidden if current_user.id != @place.user_id
    @place.destroy
    redirect_to root_path
  end

  private
  def place_params
  	return params.require(:place).permit(:name, :description, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_places = @user.places.page(params[:place_page]).per(3)
    @user_comments = @user.comments.page(params[:comment_page]).per(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_devise.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="box col-xs-4 col-xs-offset-4">
			<%= yield %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Nomster SF</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar navbar-inverse">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <%= link_to "Nomster SF", root_path, class: "navbar-brand" %>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li>
		        	<%= link_to new_place_path do %>
		        		<span class="glyphicon glyphicon-plus-sign"></span> New Nom Spot
		        	<% end %>
		        </li>
		      </ul>
		      <ul class="nav navbar-nav navbar-right">
		      	<% if user_signed_in? %>
		      		<li><%= link_to "My Profile", user_path(current_user) %></li>
		      		<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
		      	<% else %>
		      		<li><%= link_to "Sign In", new_user_session_path %></li>
		      		<li><%= link_to "Sign Up", new_user_registration_path %></li>
		      	<% end %>
		      </ul>
		    </div>
		  </div>
		</nav>

		<div class="container-fluid text-center">
			<% if flash[:notice].present? %>
				<p class="alert alert-info" role="alert"><%= flash[:notice] %></p>
			<% end %>
			<% if flash[:alert].present? %>
	        	<p class="alert alert-danger" role="alert"><%= flash[:alert] %></p>
	        <% end %>
    	</div>

		<%= controller.class.name.include?("Devise") ? render("layouts/devise") : yield %>
	</body>
</html>

app/views/places/edit.html.erb
<div class="row">
	<div class="box col-xs-10 col-xs-offset-1">
		<h1>Edit Your Place</h1>
		<br>
		<%= simple_form_for(@place, wrapper: :vertical_form, method: :put) do |f| %>
			<%= f.input :name %>
			<%= f.input :address %>
			<%= f.input :description %>
			<br>
			<%= f.submit("Update", class: "btn btn-primary") %>
		<% end %>
	</div>
</div>

app/views/places/index.html.erb
<div class="container-fluid">
	<% if !params[:page].present? || params[:page] == "1" %>
		<div class="row">
			<div class="col-xs-10 col-xs-offset-1 carousel-column">
				<div id="food-carousel" class="carousel slide center-block" data-ride="carousel">
					<!-- Selectors -->
					<ol class="carousel-indicators">
						<li data-target="#food-carousel" data-slide-to="0" class="active"></li>
						<li data-target="#food-carousel" data-slide-to="1"></li>
						<li data-target="#food-carousel" data-slide-to="2"></li>
					</ol>

					<!-- Wrapper for slides -->
					<div class="carousel-inner" role="listbox">
						<div class="item active">
							<%= image_tag "homepage_slider_1.jpg" %>
							<div class="carousel-caption">Crazy Good Curry</div>
						</div>
						<div class="item">
							<%= image_tag "homepage_slider_2.jpg" %>
							<div class="carousel-caption">Tantalizing Tea Leaf Salad</div>
						</div>
						<div class="item">
							<%= image_tag "homepage_slider_3.jpg" %>
							<div class="carousel-caption">Tremendous Tacos</div>
						</div>
					</div>

					<!-- Controls -->
					<a class="left carousel-control" href="#food-carousel" role="button" data-slide="prev">
						<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span><span class="sr-only">Previous</span>
					</a>
					<a class="right carousel-control" href="#food-carousel" role="button" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span><span class="sr-only">Next</span>
					</a>
				</div>
			</div>
		</div>
	<% end %>
	<% @places.each do |place| %>
		<div class="row">
			<div class="box col-xs-10 col-xs-offset-1">
				<h1><%= link_to place.name, place_path(place) %></h1>
				<i><%= place.address %></i>
				<br><br>
				<% if place.photos.present? %>
					<%= image_tag place.photos.last.image, class: "highlight-image" %>
				<% end %>
				<p><%= place.description %></p>
				<% if place.user.present? %>
					<small><%= place.user.email %></small>
				<% end %>
				<div class="clearfix"></div>
				<% if place.comments.present? %>
					<% comment = place.comments.last %>	
					<blockquote>
						<% (1..comment.rating).each do %>
							<span class="glyphicon glyphicon-star"></span>
						<% end %> 
						- <%= comment.message -%>
						<small><%= comment.user.email %></small>
					</blockquote>
				<% end %>
			</div>
		</div>
	<% end %>
	<%= paginate @places, params: {controller: "places", action: "index"}%>
</div>

app/views/places/new.html.erb
<div class="row">
	<div class="box col-xs-10 col-xs-offset-1">
		<h1>Enter Your Place Details</h1>
		<br>
		<%= simple_form_for(@place, wrapper: :vertical_form) do |f| %>
			<%= f.input :name %>
			<%= f.input :address %>
			<%= f.input :description %>
			<br>
			<%= f.submit("Create", class: "btn btn-primary") %>
		<% end %>
	</div>
</div>

app/views/places/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="box col-xs-10 col-xs-offset-1">
			<h1><%= @place.name %></h1>
			<i><%= @place.address %></i>
			<br><br>
			<p><%= @place.description %></p>
			<% if @place.photos.present? %>
				<div class="row">
					<% @place.photos.each do |photo| %>
						<div class="col-xs-12 col-sm-6 col-md-4">
							<div class="thumbnail">
								<%= image_tag photo.image_url(:padded), class: "img-responsive" %>
								<div class="caption text-center">
									<%= photo.caption %>
								</div>
							</div>
						</div>
					<% end %>
				</div>
			<% end %>
 			<% if @place.longitude.present? && @place.latitude.present? %>
 				<br>
				<div id="map" data-latitude="<%= @place.latitude %>" data-longitude="<%= @place.longitude %>"></div>
				<br>
			<% end %>
			<% if current_user == @place.user %>
				<div class="pull-right">
					<!-- This button triggers the photo submission modal -->
					<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myPhotoModal">Add Photo</button>
					<%= link_to "Edit Info", edit_place_path(@place), class: "btn btn-primary" %>
					<%= link_to "Delete", place_path(@place), method: :delete, data: {confirm: "Are you sure you want to delete this place?"}, class: "btn btn-primary" %>
				</div>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="box col-xs-10 col-xs-offset-1">
			<!-- This button triggers the comment submission modal -->
			<button type="button" class="btn btn-primary add-comment-btn" data-toggle="modal" data-target="#myCommentModal">Add Comment</button>
			<h2>Comments</h2>
			<% @place.comments.each do |comment| %>
				<blockquote>
					<% (1..comment.rating).each do %>
						<span class="glyphicon glyphicon-star"></span>
					<% end %> 
					- <%= comment.message -%>
					<small><%= comment.user.email %></small>
				</blockquote>
			<% end %>
		</div>
	</div>
</div>

<!-- Photo submission modal -->
<div class="modal fade" id="myPhotoModal" tabindex="-1" role="dialog" aria-labelledby="myPhotoModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myPhotoModalLabel">Add Your Photo</h4>
			</div>
			<%= simple_form_for @photo, wrapper: :vertical_form, url: place_photos_path(@place) do |f| %>
				<div class="modal-body">
					<%= f.input :image %>
					<%= f.input :caption, label: "Caption (140 characters max)" %>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<%= f.submit "Add Photo", class: "btn btn-primary" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<!-- Comment submission modal -->
<div class="modal fade" id="myCommentModal" tabindex="-1" role="dialog" aria-labelledby="myCommentModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myCommentModalLabel">Add Your Comment</h4>
			</div>
			<%= simple_form_for @comment, wrapper: :vertical_form, url: place_comments_path(@place) do |f| %>
				<div class="modal-body">
					<% unless current_user %>
						<p><strong>You must be signed in to comment</strong></p>
					<% end %>
					<%= f.input :message %>
					<%= f.input :rating, collection: Comment::RATING_MAP, include_blank: false %>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<%= f.submit "Add Comment", class: "btn btn-primary" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
	<div class="col-xs-10 col-xs-offset-1 box">
		<h1>Nomster SF Profile</h1>
		<br>
		<div class="row">
			<div class="col-xs-4">
				<%= image_tag "user_logo.svg", class: "user-logo" %>
			</div>
			<div class="col-xs-8 text-center">
				<br>
				<h3 class="user-email"><%= @user.email %></h3>
				<h4>Member Since: <%= @user.created_at.strftime "%B %d, %Y" %></h4>
				<br>
				<h4><%= @user.places.count %> total places</h4>
				<h4><%= @user.comments.count %> total comments</h4>
				<h4>
					<%= @user.comments.select {|comment| comment.rating == 5}.count %> total <span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span> reviews
				</h4>
			</div>
		</div>
		<% if @user_places.present? %>
			<br><br>
			<h2 class="text-center">Places Created</h2>
			<br>
			<% @user_places.each do |place| %>
				<h1><%= link_to place.name, place_path(place) %></h1>
				<i><%= place.address %></i>
				<br><br>
				<% if place.photos.present? %>
					<%= image_tag place.photos.last.image, class: "highlight-image" %>
				<% end %>
				<p><%= place.description %></p>
				<small><%= place.user.email %></small>
				<div class="clearfix"></div>
				<hr>
			<% end %>
			<%= paginate @user_places, param_name: "place_page" %>
		<% end %>
		<% if @user_comments.present? %>
			<br><br>
			<h2 class="text-center">Comments Made</h2>
			<br>
			<% @user_comments.each do |comment| %>
				This is a comment on <%= link_to comment.place.name, place_path(comment.place) %>
				<blockquote class="user-comment">
					<% (1..comment.rating).each do %>
						<span class="glyphicon glyphicon-star"></span>
					<% end %> 
					- <%= comment.message -%>
					<small><%= comment.user.email %></small>
				</blockquote>
			<% end %>
			<%= paginate @user_comments, param_name: "comment_page" %>
		<% end %>
	</div>
</div>